### ISSUE TITLE
Example cannot be installed with python 3.12+ because of missing distutils

### ISSUE THREAD

**Issue by HumanUser** [gravity-ui/yagr#232]
```npm error gyp info spawn args ]
npm error Traceback (most recent call last):
npm error   File "/Users/<username>/git/yagr/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error     ^^^^^^^^^^
npm error   File "/Users/<username>/git/yagr/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/Users/<username>/git/yagr/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm error     from distutils.version import StrictVersion```

**Comment by Estasie** [comment]
[this can temporary help](https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed)
